{% set name = "graphql-js" %}
{% set version = "15.1.0" %}
{% set sha256 = "b4cf8680faa57227ff9bdc0a53af20497d6c29a94584c3b14365b8e9dc5dc085" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/graphql/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs

test:
  commands:
    - npm list -g graphql
  requires:
    - nodejs

about:
  home: https://github.com/graphql/graphql-js
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A reference implementation of GraphQL for JavaScript
  description: |
    The JavaScript reference implementation for GraphQL, a query language for APIs created by Facebook. 
  doc_url: http://graphql.org/graphql-js/
  dev_url: https://github.com/graphql/graphql-js
