{% set name = "graphql-js" %}
{% set version = "14.5.8" %}
{% set sha256 = "22802ece7a48aa6423f3ac78405063ed1eca5bc635e0bb2cdbeb7782789af965" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/graphql/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g graphql
  requires:
    - nodejs
   
about:
  home: https://github.com/graphql/graphql-js
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A reference implementation of GraphQL for JavaScript'
  description: |
    The JavaScript reference implementation for GraphQL, a query language for APIs created by Facebook. 
  doc_url: http://graphql.org/graphql-js/
  dev_url: https://github.com/graphql/graphql-js
  
extra:
  recipe-maintainers:
    - cshaley
    - sannykr
