travis:
  secure:
    BINSTAR_TOKEN: l2p76jFqAnjoyNk6CEx/I4c7kwxZzkbNZmOD6zYMYTxzPqLtpkoiuqPIaMsUIcNc2as99EuBhylwzCEFHNEG8jqAfSvNF7bapisMlQiBZGYuwHSJNfr3ZV7H8ud5bGHsDRbvIrDpt2wfUmBbQaL/KmB0BG9MYOpfGDyakYl0AWuWg1FYDhzoGTvhdLyBRiEr4F+PEfn33MZlvXMPi1OUIYN4t4rVt786wyJicYpGSrAh4CcY6d1EfQbARz0yFLr6wLFXrpPcoWN2h6kJlJ+cpyr4LtvZCVvWljfQTKziaNgjJe8r2JxowpJdvd9irGDSlTc/2rrJDknTzCBpWJK9lRYRkH+viEar+nSJoB7qphku1p/6pZsJ0DGWDhRKUhrIst17cqZ94Y1eI3zSh0GKzTUEwoHhuKd560NgUH0qtVeUuGOSpyNzSYsDm1Mj+FjMBsvwaeCwfNQw5LEbjcXFKrFTXTO0rUEYR0QqMC/+dwchAkaiJ604qoW4I4GWAM6SN/Xtc7G8yC5JilmMWFIDbedQYx2a8cPGP8MQOhqkvOpqAmI2DD5DoRfqH3jaohqKrHh+XlalwY1onDhQQ0BhEVmuzNbXlZUkkGC5WAvcknY3kksfbhXyzk0UGAmLrSNLbvnLFu494kOFDb1Qk3Sm+dD2I/AXw13Qya3Q1MOfxBg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
