travis:
  secure:
    BINSTAR_TOKEN: H2p5FgdoDWCyUG58YH/OVlJ4k4t6zLcgGNrKp5Ca+igduym144qwIO8v+ogn4VpdV1b5+vc6QXyM2S6QOkodUBI7KDgIJe3LR5zZB8p0/5graqoSKEHr52SKWs4wZ9MDRSoiCyAw8DPQvXuxe2SMyUKXHTHhkVgWOHZZAHaSql7HT2VhfU+EF0+SvYPN8Hgd/4RuzG/379Z3TuCMPW9rVrrDmqaYONfLIz2HAwELWBNY3+FxIxtDPDOiFTpbuihlDSEYKo04UMWJiFih7aoQ0GvHJTqbMJkVuueGt7b4JEr8249Z5RZPrfSApJ5aatsUMWMUE/CzxcF7ETINh6r0O6QkNi3Neg/yswWz6tvw1X9HJK/VLFeiuEtcI596XGD2wDGYMNUVgv6Mw/PkBGSfNsQnQpkymIGSjdjX9uNyDE+2eW5PhFDUY/rETHMwKOh3CxV9/UcBE8G1M9mBJzSHDdte3FCVfqLI13Nyl+VlT5K4hh/O6Hl/0kITDRQp1+1psdjuWWK/aYRnMESCRa5ypTvUheSOGE8HSQNZmTmXK6s06CeHiT9hnpuvJ/GIuTT4qx9vxIOO6NtXCcj6yDdc/2N0eQvumfalO/Pat/CRU0TDdmaBp7Q1KhRUWvC6V2kr/aVrP166tlnMP1hxWcX9FqIJ/fbo13b9GW+Lg9xFGow=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
