travis:
  secure:
    BINSTAR_TOKEN: muqaGfIUQJGaexeRPcDQeQYS4A/WMVGnQgAufCtIUA2g47pCAgCFapM7h8LTVh82e1WxU1v9bVVrb/w4IJe+WGxZ/UTXXo7dss6tsglfxYBsFBpu6lrDxOWjaKv+pz+WwDQkikwgqXttxsewcynfAU0EXSi27mO+4Auj+eWMqciqYrFXYegUpwxDJOu2Bt0F8USgq64E2G5jcA1u7VZ90+8Dj5dRufC2Bc4grsU8Ks6D2AC8AEipUQvj8uNB3MRvodIA9dJZb2q1H8ZbGJ7j0E/crAVBv8geoiZ1ZWsRSqlW4qK6JlYnqBjXkoKt7AXSViCHL8abcB9ohKSYjBQtpxDZ/SDYnaEa1+dJ7Kh+AbXgf2sBdzyd0IKPwHg9cj/osy6JtMrXy5zlZulT3M/m92yN1fdpqYMGW8Y4CNnCwQQu1/1RIvW9BCTx5cjaKuGQjFgHX+iBQWD8YVhvmLy3b0f7XUZ2/aXmFKz3QrOjvURdlxhmgqbb0l1y+On+Q7ukOnf+5rDO7+sN6UwKzTD6VCyDEaNRQrtIUrr6jqmNvFgm+r60BXS7YPkwYsuDtz1a8w8pMqMT/nWNl2XuEKagdDV5o0xU0ap9uXqHKGPgh64/dfvxNZZQvKpmSzYIb4ftwCevchZuewuYY33cI+QiPdqG7BqBF79ap6SPK237AMk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
