travis:
  secure:
    BINSTAR_TOKEN: qcG6LkkG6SVnc0Z2ftcJQFYDGx5jGalyyPo4DOgpKhBoNq5vfFHfIfzvPck8n+JJBwbV6al36FwAVkAc9XptZsjByKABH9JwbT7kBJmPS6zORXJGsY6IrIzqVJCHj4xns3knhmfG+bBuwMTtmowDXT6h+6dfXDLrVAI94ZpvE/28GUBuhs6JZBnP7GSwA8T/FQuFmv5fJw01ENEKnlxE1uuwVhBK2FZQ1HH8KjdlIBC1yeNvRZskTzfHPrr9RiBKH4ExPLxae9EdLJqd2Ji4+6Zv4r5ILsLI8YZqSqlmgMP8W35Rv/JenLR+yjaCn/xUMxzwVTDd6BJ/TnqPQ9XVxRAggnEc8H7uaiwdSWBRsRsNv75CEGLITZrlOA2o6jDNKbgGwTAJVAmE1VMnMbfdFuuZMMdJSlHKHREapbo4TKoAMzQyLQUGa+5Fk1MJI0FLiwGdKgOK7IFdZMYlfNLOyUgcLhsV4oI32LmPvCks4CxBdk5Nyto7Hqaz2Nt8OUEKghGFfzsY7nO5lZd8mN9tJf1RhpKa1J00fEMpnw7XvohSw9jhc9hrwzyMuvST2HNb6MoPzbD3eJVT1oCDnMmXUCD5m7nyMvnwnv7xbWgmqmVq565EP7cG2UVPPQYBzq3Er3Ggt/DccVcIlOdAYp3KmGAiD+bEuTecL88kQ3poRLc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
