travis:
  secure:
    BINSTAR_TOKEN: EhD9MmoDk1uqojXi2kw9uFhr+N4BT5WbBvw9sbZxLZAtHhhEAxlC+8w4OugIWVaqRw/rFQxCat+uKAN/FStPitkf9m3fJ8/spJ6aKRZdLc/UJ2WQAHsKvQ7Z+TeCiy24I2HaJU8NQKMbBV5VIusb37JaY+l/vkGD8ViZfJLoXnVtgRAHtM6KeebU5z2hwSDxPRTX+kD76+szGC4WXeFkx+0HK70Umm0We/aWSOx1G7PviLPtsqyc9wxfrcp31NK3Na1dTCyWJfLBz3xBUEshVlubNGGn1LK1aNfeW2fiW66fkuCRrzGYBwAaPtnZF6e+SNR/Ql/mpv3A25eWBYYx+8a0XlSW3qOyHKTixTbcJuO83cYuBdhf76El1tF3GNVykuLAkeFy2EcSYQ6F+4nTZtvSPmPQcgGBR76udb3z61eYq88dvtJnRJ8Q4bVbtfnjus1cNvneIfhIiSLTMbSjMCi5iFo++OqdsERiPOuJtCH54PhO/35KhMwMRfMMYhJ0KtphzS0ayFyKqH9yb2Bcl9YmSZBu8T4D6mlbUHi9JElcCa42oB0yVrigNT+hk+OmQ5HWTyfxtEb4sakmG46LpTTw7TMLmDVVDbV07QdDtWo3la21nWz7wUiKHEHnwm3JJ4JnlEgxZRnFm/LL2sE+2zg6NEHAaWwZSD4HZNvyDyY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
